"use client";
import { useEffect, useState } from "react";
type Ticket=Record<string,any>;
type Comment={id:string;author_name:string;body:string;created_at:string};
type Audit={id:string;actor:string;action:string;details:any;created_at:string};

export default function TicketDetail({params}:{params:Promise<{ticketNo:string}>}){
 const [ticketNo,setTicketNo]=useState(""),[ticket,setTicket]=useState<Ticket|null>(null),[comments,setComments]=useState<Comment[]>([]),[audit,setAudit]=useState<Audit[]>([]);
 const [aiAnswer,setAiAnswer]=useState(""),[aiSources,setAiSources]=useState<{title:string;path:string;url:string}[]>([]),[aiLoading,setAiLoading]=useState(false);\n const [status,setStatus]=useState(""),[assignee,setAssignee]=useState(""),[priority,setPriority]=useState(""),[resolution,setResolution]=useState(""),[comment,setComment]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{params.then(p=>setTicketNo(p.ticketNo))},[params]);
 const refresh=async()=>{const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo));const j=await r.json();if(r.ok){setTicket(j.ticket);setComments(j.comments||[]);setAudit(j.audit||[]);}};
 useEffect(()=>{if(!ticketNo)return;refresh().then(()=>{}).catch(e=>setMessage(e.message))},[ticketNo]);
 useEffect(()=>{if(ticket){setStatus(ticket.status);setAssignee(ticket.assignee||"");setPriority(ticket.priority);setResolution(ticket.resolution||"")}},[ticket]);
 async function analyzeAI(){setAiLoading(true);setMessage("");try{const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo)+"/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({ticketNo})});const j=await r.json();if(!r.ok)throw new Error(j.error);setAiAnswer(j.answer||"");setAiSources(j.sources||[])}catch(e){setMessage(e instanceof Error?e.message:"AI analysis failed")}finally{setAiLoading(false)}}\n async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,assignee,priority,resolution,actor:"IT Helpdesk"})});const j=await r.json();if(!r.ok)throw new Error(j.error);setMessage("Đã cập nhật Ticket.");await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Lỗi cập nhật")}finally{setSaving(false)}}
 async function addComment(e:React.FormEvent){e.preventDefault();if(!comment.trim())return;const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo)+"/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:comment,author_name:"IT Helpdesk"})});const j=await r.json();if(!r.ok){setMessage(j.error);return}setComment("");setMessage("Đã thêm ghi chú.");await refresh()}
 if(!ticket)return <main className="container"><a href="/tickets">← Danh sách Ticket</a><div className="panel"><p>{message||"Đang tải..."}</p></div></main>;
 return <main className="container"><div className="hero"><a href="/tickets">← Danh sách Ticket</a><h1>{ticket.ticket_no}</h1><p>{ticket.title}</p></div>
 <div className="detail-grid"><section className="panel"><h2>Thông tin yêu cầu</h2><dl className="detail-list"><dt>Mô tả</dt><dd>{ticket.description||"-"}</dd><dt>Người yêu cầu</dt><dd>{ticket.requester_name||"-"} {ticket.requester_email?"("+ticket.requester_email+")":""}</dd><dt>Đơn vị</dt><dd>{ticket.unit||"-"}</dd><dt>Thiết bị</dt><dd>{ticket.asset||"-"}</dd><dt>Loại</dt><dd>{ticket.category}</dd><dt>Tạo lúc</dt><dd>{new Date(ticket.created_at).toLocaleString("vi-VN")}</dd><dt>SLA</dt><dd>{ticket.sla_due_at?new Date(ticket.sla_due_at).toLocaleString("vi-VN"):"-"}</dd></dl></section>
 <section className="panel form"><h2>Xử lý Ticket</h2><div className="ai-box"><strong>🤖 AI Helpdesk</strong><p>Phân tích Ticket dựa trên Knowledge Base và đề xuất hướng xử lý.</p><button type="button" onClick={analyzeAI} disabled={aiLoading}>{aiLoading?"Đang phân tích...":"Phân tích bằng AI"}</button>{aiAnswer&&<div className="ai-answer">{aiAnswer}</div>}{aiSources.length>0&&<div className="ai-sources"><strong>KB tham khảo</strong>{aiSources.map(s=><a key={s.path} href={s.url} target="_blank" rel="noreferrer">{s.title} — {s.path}</a>)}</div>}</div><label>Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}><option>Open</option><option>Assigned</option><option>In Progress</option><option>Resolved</option><option>Closed</option></select></label><label>Phụ trách<input value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="Tên nhân sự IT"/></label><label>Ưu tiên<select value={priority} onChange={e=>setPriority(e.target.value)}><option>Low</option><option>Normal</option><option>High</option><option>Critical</option></select></label><label>Phương án xử lý / Kết quả<textarea rows={7} value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Ghi nhận nguyên nhân và cách xử lý..."/></label><button onClick={save} disabled={saving}>{saving?"Đang lưu...":"Lưu cập nhật"}</button>{message&&<div className="notice">{message}</div>}</section></div>
 <div className="detail-grid"><section className="panel"><h2>Trao đổi / Ghi chú</h2><form onSubmit={addComment}><textarea rows={4} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Nhập nội dung trao đổi..."/><br/><button>+ Thêm ghi chú</button></form><div className="timeline">{comments.map(c=><article key={c.id}><strong>{c.author_name}</strong><small>{new Date(c.created_at).toLocaleString("vi-VN")}</small><p>{c.body}</p></article>)}{!comments.length&&<p>Chưa có ghi chú.</p>}</div></section>
 <section className="panel"><h2>Lịch sử xử lý</h2><div className="timeline">{audit.map(a=><article key={a.id}><strong>{a.action}</strong><small>{a.actor+" · "+new Date(a.created_at).toLocaleString("vi-VN")}</small><p>{a.details?JSON.stringify(a.details):""}</p></article>)}{!audit.length&&<p>Chưa có lịch sử.</p>}</div></section></div></main>;
}
