"use client";
import { useEffect, useState } from "react";
import AICopilot from "./AICopilot";
type Ticket=Record<string,any>;
type Comment={id:string;author_name:string;body:string;created_at:string};
type Audit={id:string;actor:string;action:string;details:any;created_at:string};
const statusVi:Record<string,string>={Open:"Mở",Assigned:"Đã phân công","In Progress":"Đang xử lý",Resolved:"Đã giải quyết",Closed:"Đã đóng"};
const priorityVi:Record<string,string>={Low:"Thấp",Normal:"Bình thường",High:"Cao",Critical:"Khẩn cấp"};
const categoryVi:Record<string,string>={Other:"Khác",Hardware:"Phần cứng",Software:"Phần mềm",Network:"Mạng",Printer:"Máy in",Account:"Tài khoản",Email:"Thư điện tử",Security:"An toàn thông tin"};
const slug=(x:string)=>(x||"").toLowerCase().replace(/\s+/g,"-");
function auditTitle(action:string){if(action==="Ticket created")return "Tạo yêu cầu";if(action==="Ticket updated")return "Cập nhật yêu cầu";if(action==="Comment added")return "Thêm trao đổi";return action}
function auditDetails(a:Audit){const d=a.details||{};if(a.action==="Ticket created")return <span>Yêu cầu được tạo và bắt đầu tiếp nhận xử lý.</span>;if(a.action==="Comment added")return <span>Đã thêm một nội dung trao đổi vào yêu cầu.</span>;const parts:string[]=[];if(d.status)parts.push(`Trạng thái: ${statusVi[d.status.from]||d.status.from||"-"} → ${statusVi[d.status.to]||d.status.to||"-"}`);if(d.assignee)parts.push(`Phụ trách: ${d.assignee.from||"Chưa phân công"} → ${d.assignee.to||"Chưa phân công"}`);if(d.priority)parts.push(`Ưu tiên: ${priorityVi[d.priority.from]||d.priority.from||"-"} → ${priorityVi[d.priority.to]||d.priority.to||"-"}`);if(d.resolution)parts.push(`Kết quả xử lý: ${d.resolution.to||"-"}`);return parts.length?<ul>{parts.map((x,i)=><li key={i}>{x}</li>)}</ul>:<span>Có thay đổi thông tin yêu cầu.</span>}
function slaInfo(t:Ticket){if(!t.sla_due_at)return {label:"Chưa thiết lập",kind:"neutral"};if(["Resolved","Closed"].includes(t.status))return {label:"Đã xử lý",kind:"ok"};const d=new Date(t.sla_due_at).getTime()-Date.now();if(d<0)return {label:"Quá thời hạn",kind:"overdue"};if(d<=3600000)return {label:"Sắp quá hạn",kind:"soon"};return {label:"Trong thời hạn",kind:"ok"}}
export default function TicketDetail({params}:{params:Promise<{ticketNo:string}>}){
 const [ticketNo,setTicketNo]=useState(""),[ticket,setTicket]=useState<Ticket|null>(null),[comments,setComments]=useState<Comment[]>([]),[audit,setAudit]=useState<Audit[]>([]);const [status,setStatus]=useState(""),[assignee,setAssignee]=useState(""),[priority,setPriority]=useState(""),[resolution,setResolution]=useState(""),[comment,setComment]=useState(""),[message,setMessage]=useState(""),[saving,setSaving]=useState(false);
 useEffect(()=>{params.then(p=>setTicketNo(p.ticketNo))},[params]);const refresh=async()=>{const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo));const j=await r.json();if(r.ok){setTicket(j.ticket);setComments(j.comments||[]);setAudit(j.audit||[])}else throw new Error(j.error||"Không tìm thấy yêu cầu")};useEffect(()=>{if(!ticketNo)return;refresh().catch(e=>setMessage(e instanceof Error?e.message:"Lỗi tải yêu cầu"))},[ticketNo]);useEffect(()=>{if(ticket){setStatus(ticket.status);setAssignee(ticket.assignee||"");setPriority(ticket.priority);setResolution(ticket.resolution||"")}},[ticket]);
 async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo),{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,assignee,priority,resolution,actor:"IT Helpdesk"})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Lỗi cập nhật");setMessage("Đã lưu cập nhật.");await refresh()}catch(e){setMessage(e instanceof Error?e.message:"Lỗi cập nhật")}finally{setSaving(false)}}
 async function addComment(e:React.FormEvent){e.preventDefault();if(!comment.trim())return;const r=await fetch("/api/tickets/"+encodeURIComponent(ticketNo)+"/comments",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({body:comment,author_name:"IT Helpdesk"})});const j=await r.json();if(!r.ok){setMessage(j.error||"Lỗi thêm ghi chú");return}setComment("");setMessage("Đã thêm ghi chú.");await refresh()}
 if(!ticket)return <main className="container"><a className="back-link" href="/tickets">← Danh sách yêu cầu</a><div className="panel"><p>{message||"Đang tải..."}</p></div></main>;
 const sla=slaInfo(ticket);
 return <main className="container ticket-detail-page"><div className="ticket-detail-head"><div><a className="back-link" href="/tickets">← Danh sách yêu cầu</a><div className="ticket-code-row"><span className="ticket-code">{ticket.ticket_no}</span><span className={"status-badge status-"+slug(ticket.status)}>{statusVi[ticket.status]||ticket.status}</span><span className={"priority-badge priority-"+slug(ticket.priority)}>{priorityVi[ticket.priority]||ticket.priority}</span></div><h1>{ticket.title}</h1><p>Tạo lúc {new Date(ticket.created_at).toLocaleString("vi-VN")}</p></div><div className={"sla-summary "+sla.kind}><span>Thời hạn xử lý</span><strong>{sla.label}</strong><small>{ticket.sla_due_at?new Date(ticket.sla_due_at).toLocaleString("vi-VN"):"Chưa có thời hạn"}</small></div></div>
 <div className="ticket-workspace"><div className="ticket-main-column"><section className="panel ticket-info-panel"><div className="panel-title-row"><div><h2>Thông tin yêu cầu</h2><p>Thông tin do người yêu cầu cung cấp</p></div></div><div className="ticket-description"><span>Mô tả sự cố / yêu cầu</span><p>{ticket.description||"Chưa có mô tả."}</p></div><div className="info-grid"><div><span>Người yêu cầu</span><strong>{ticket.requester_name||"-"}</strong><small>{ticket.requester_email||""}</small></div><div><span>Đơn vị / Nhà máy</span><strong>{ticket.unit||"-"}</strong></div><div><span>Thiết bị</span><strong>{ticket.asset||"-"}</strong></div><div><span>Loại yêu cầu</span><strong>{categoryVi[ticket.category]||ticket.category||"-"}</strong></div></div></section>
 <AICopilot ticketNo={ticketNo} onResolution={setResolution}/>
 <section className="panel comments-panel"><div className="panel-title-row"><div><h2>Trao đổi và ghi chú</h2><p>Ghi nhận nội dung phối hợp trong quá trình xử lý</p></div><span className="history-count">{comments.length} ghi chú</span></div><form className="comment-form" onSubmit={addComment}><textarea rows={3} value={comment} onChange={e=>setComment(e.target.value)} placeholder="Nhập nội dung trao đổi hoặc ghi chú xử lý..."/><button type="submit">+ Thêm ghi chú</button></form><div className="comment-list">{comments.map(c=><article key={c.id}><span className="table-avatar">{c.author_name?.charAt(0)?.toUpperCase()||"I"}</span><div><div className="comment-meta"><strong>{c.author_name}</strong><time>{new Date(c.created_at).toLocaleString("vi-VN")}</time></div><p>{c.body}</p></div></article>)}{!comments.length&&<div className="empty-note">Chưa có trao đổi hoặc ghi chú.</div>}</div></section>
 <section className="panel history-panel"><div className="panel-title-row"><div><h2>Lịch sử xử lý</h2><p>Toàn bộ thay đổi được hệ thống ghi nhận tự động</p></div><span className="history-count">{audit.length} sự kiện</span></div><div className="audit-timeline modern-audit">{audit.map(a=><article key={a.id} className="audit-item"><div className="audit-marker"/><div className="audit-card"><div className="audit-top"><strong>{auditTitle(a.action)}</strong><time>{new Date(a.created_at).toLocaleString("vi-VN")}</time></div><div className="audit-actor">Thực hiện bởi <strong>{a.actor}</strong></div><div className="audit-details">{auditDetails(a)}</div></div></article>)}{!audit.length&&<div className="empty-note">Chưa có lịch sử xử lý.</div>}</div></section></div>
 <aside className="ticket-side-column"><section className="panel form resolution-panel"><div className="panel-title-row"><div><h2>Cập nhật xử lý</h2><p>Phân công và cập nhật kết quả</p></div></div><label>Trạng thái<select value={status} onChange={e=>setStatus(e.target.value)}><option value="Open">Mở</option><option value="Assigned">Đã phân công</option><option value="In Progress">Đang xử lý</option><option value="Resolved">Đã giải quyết</option><option value="Closed">Đã đóng</option></select></label><label>Người phụ trách<input value={assignee} onChange={e=>setAssignee(e.target.value)} placeholder="Tên nhân sự CNTT"/></label><label>Mức ưu tiên<select value={priority} onChange={e=>setPriority(e.target.value)}><option value="Low">Thấp</option><option value="Normal">Bình thường</option><option value="High">Cao</option><option value="Critical">Khẩn cấp</option></select></label><label>Phương án / Kết quả xử lý<textarea rows={8} value={resolution} onChange={e=>setResolution(e.target.value)} placeholder="Ghi nhận nguyên nhân, thao tác và kết quả xử lý..."/></label><button type="button" onClick={save} disabled={saving}>{saving?"Đang lưu...":"Lưu cập nhật"}</button>{message&&<div className="notice">{message}</div>}</section></aside></div>
 </main>;
}