"use client";
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Doc={title:string;path:string;type:"knowledge"|"case"|"script";content:string};
type Heading={id:string;text:string;level:number};
const typeLabel:Record<string,string>={knowledge:"Tài liệu kỹ thuật",case:"Tình huống xử lý",script:"Công cụ / Script"};
const makeId=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");
function headings(md:string):Heading[]{return md.split(/\r?\n/).filter(x=>/^#{1,3}\s+/.test(x)).map((x,i)=>{const m=x.match(/^(#{1,3})\s+(.+)$/)!;return{id:makeId(m[2])+"-"+i,text:m[2],level:m[1].length}})}
function renderMarkdown(md:string){const hs=headings(md);let hi=0;const lines=md.replace(/\r\n/g,"\n").split("\n");const out:React.ReactNode[]=[];let code=false;let buf:string[]=[];const flush=()=>{if(buf.length){out.push(<pre className="kb-code" key={"code-"+out.length}><code>{buf.join("\n")}</code></pre>);buf=[]}};lines.forEach((line,i)=>{if(line.trim().startsWith("```")){if(code)flush();code=!code;return}if(code){buf.push(line);return}if(/^#{1,3}\s+/.test(line)){const h=hs[hi++];if(h.level===1)out.push(<h1 id={h.id} key={i}>{h.text}</h1>);else if(h.level===2)out.push(<h2 id={h.id} key={i}>{h.text}</h2>);else out.push(<h3 id={h.id} key={i}>{h.text}</h3>)}else if(/^[-*]\s+/.test(line))out.push(<li key={i}>{line.replace(/^[-*]\s+/,"")}</li>);else if(/^\d+\.\s+/.test(line))out.push(<li key={i}>{line.replace(/^\d+\.\s+/,"")}</li>);else if(/^>\s?/.test(line))out.push(<blockquote key={i}>{line.replace(/^>\s?/,"")}</blockquote>);else if(line.trim())out.push(<p key={i}>{line}</p>)});if(code)flush();return out}
export default function KnowledgeDocument({path}:{path:string}){const[doc,setDoc]=useState<Doc|null>(null),[error,setError]=useState(""),[question,setQuestion]=useState(""),[answer,setAnswer]=useState(""),[asking,setAsking]=useState(false),[ticketMsg,setTicketMsg]=useState("");useEffect(()=>{fetch("/api/knowledge/document?path="+encodeURIComponent(path)).then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể tải tài liệu");return j.document}).then(setDoc).catch(e=>setError(e.message))},[path]);const toc=useMemo(()=>doc?headings(doc.content):[],[doc]);async function askAI(){if(!doc||!question.trim())return;setAsking(true);setAnswer("");try{const r=await fetch("/api/ai/copilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:`Dựa ưu tiên vào tài liệu ${doc.title} (${doc.path}), hãy trả lời: ${question}`,history:[]})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể gọi trợ lý AI");setAnswer(j.answer||"")}catch(e){setAnswer(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setAsking(false)}}async function createTicket(){if(!doc)return;setTicketMsg("Đang tạo yêu cầu...");try{const r=await fetch("/api/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:(question||doc.title).slice(0,255),description:`Tài liệu tham khảo: ${doc.title}\n${doc.path}\n\nCâu hỏi: ${question||"Cần hỗ trợ thêm về tài liệu này"}\n\nGợi ý AI: ${answer}`,category:"Other",priority:"Normal"})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể tạo yêu cầu");setTicketMsg(`Đã tạo ${j.ticket.ticket_no}`)}catch(e){setTicketMsg(e instanceof Error?e.message:"Không thể tạo yêu cầu")}}
if(error)return <main className="container"><div className="panel kb-empty"><strong>{error}</strong><p><Link href="/knowledge-base">← Quay lại Kho kiến thức</Link></p></div></main>;if(!doc)return <main className="container"><div className="panel kb-loading">Đang tải tài liệu...</div></main>;return <main className="container kb-reader-page"><div className="kb-detail-top"><Link href="/knowledge-base">← Kho kiến thức</Link><span>{typeLabel[doc.type]}</span></div><header className="kb-reader-head"><div><span className={"badge badge-"+doc.type}>{typeLabel[doc.type]}</span><h1>{doc.title}</h1><p>{doc.path}</p></div><div className="kb-reader-actions"><button type="button" onClick={()=>document.getElementById("hoi-ai")?.scrollIntoView({behavior:"smooth"})}>Hỏi AI về tài liệu</button><button className="kb-secondary" type="button" onClick={createTicket}>Tạo yêu cầu hỗ trợ</button></div></header><div className="kb-reader-layout"><aside className="kb-toc"><strong>Mục lục</strong>{toc.length?toc.map(h=><a key={h.id} className={h.level===3?"toc-sub":""} href={"#"+h.id}>{h.text}</a>):<span>Tài liệu không có đề mục.</span>}</aside><article className="panel kb-document modern-document">{renderMarkdown(doc.content)}</article><aside className="kb-reader-side"><section className="panel kb-doc-meta"><strong>Thông tin tài liệu</strong><div><span>Loại</span><b>{typeLabel[doc.type]}</b></div><div><span>Đường dẫn</span><b>{doc.path}</b></div><div><span>Nguồn</span><b>Kho kiến thức nội bộ</b></div></section><section id="hoi-ai" className="panel kb-doc-ai"><span className="kb-ai-logo">AI</span><h3>Hỏi về tài liệu này</h3><p>Đặt câu hỏi để trợ lý phân tích nội dung và đề xuất hướng xử lý.</p><textarea rows={4} value={question} onChange={e=>setQuestion(e.target.value)} placeholder="Ví dụ: Tôi cần thực hiện các bước nào trước?"/><button type="button" onClick={askAI} disabled={asking||!question.trim()}>{asking?"Đang phân tích...":"Hỏi Trợ lý AI"}</button>{answer&&<div className="kb-doc-answer">{answer}</div>}{answer&&<button className="kb-secondary" type="button" onClick={createTicket}>Tạo yêu cầu từ nội dung này</button>}{ticketMsg&&<div className="notice">{ticketMsg}</div>}</section></aside></div></main>}
