"use client";
import { useEffect,useMemo,useState } from "react";
type Ticket={ticket_no:string;title:string;unit:string;category:string;priority:string;status:string;assignee:string|null;sla_due_at:string|null};
const statuses=[["All","Tất cả"],["Open","Mở"],["Assigned","Đã phân công"],["In Progress","Đang xử lý"],["Resolved","Đã giải quyết"],["Closed","Đã đóng"]];
const priorities=[["All","Tất cả"],["Critical","Khẩn cấp"],["High","Cao"],["Normal","Bình thường"],["Low","Thấp"]];
const categories:Record<string,string>={Other:"Khác",Hardware:"Phần cứng",Software:"Phần mềm",Network:"Mạng",Printer:"Máy in",Account:"Tài khoản",Email:"Thư điện tử",Security:"An toàn thông tin"};
const priorityLabel=(x:string)=>priorities.find(p=>p[0]===x)?.[1]||x;
const statusLabel=(x:string)=>statuses.find(s=>s[0]===x)?.[1]||x;
function slaLabel(x:Ticket){if(!x.sla_due_at||x.status==="Resolved"||x.status==="Closed")return "Đã xử lý";const d=new Date(x.sla_due_at).getTime()-Date.now();return d<0?"Quá thời hạn":d<=3600000?"Sắp quá hạn":"Trong thời hạn"}
export default function Tickets(){const [rows,setRows]=useState<Ticket[]>([]),[q,setQ]=useState(""),[status,setStatus]=useState("All"),[priority,setPriority]=useState("All"),[sla,setSla]=useState("All"),[error,setError]=useState("");
 async function load(){const qs=new URLSearchParams();if(status!=="All")qs.set("status",status);if(priority!=="All")qs.set("priority",priority);if(sla!=="All")qs.set("sla",sla);const r=await fetch("/api/tickets?"+qs.toString());const j=await r.json();if(!r.ok){setError(j.error||"Không thể tải danh sách yêu cầu");return}setRows(j.tickets||[])}
 useEffect(()=>{load()},[status,priority,sla]);
 const filtered=useMemo(()=>rows.filter(x=>Object.values(x).join(" ").toLowerCase().includes(q.toLowerCase())),[rows,q]);
 return <main className="container"><div className="hero"><span className="eyebrow">Hệ thống hỗ trợ CNTT</span><h1>Yêu cầu hỗ trợ</h1><p>Quản lý yêu cầu hỗ trợ và sự cố CNTT.</p><a className="button" href="/tickets/new">+ Tạo yêu cầu</a>{error&&<div className="notice">{error}</div>}</div>
 <section className="panel"><div className="toolbar ticket-filters"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm yêu cầu, đơn vị, thiết bị..."/><select value={status} onChange={e=>setStatus(e.target.value)}>{statuses.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={priority} onChange={e=>setPriority(e.target.value)}>{priorities.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select><select value={sla} onChange={e=>setSla(e.target.value)}><option value="All">Tất cả thời hạn</option><option value="overdue">Quá thời hạn</option><option value="soon">Sắp quá hạn</option><option value="ontrack">Trong thời hạn</option></select></div>
 <div className="table-wrap"><table><thead><tr><th>Mã yêu cầu</th><th>Tiêu đề</th><th>Đơn vị</th><th>Loại</th><th>Ưu tiên</th><th>Trạng thái</th><th>Thời hạn</th><th>Phụ trách</th></tr></thead><tbody>{filtered.map(x=><tr key={x.ticket_no}><td><a href={"/tickets/"+encodeURIComponent(x.ticket_no)}><strong>{x.ticket_no}</strong></a></td><td>{x.title}</td><td>{x.unit||"-"}</td><td>{categories[x.category]||x.category}</td><td>{priorityLabel(x.priority)}</td><td>{statusLabel(x.status)}</td><td><span className={"sla-badge sla-"+(slaLabel(x)==="Quá thời hạn"?"overdue":slaLabel(x)==="Sắp quá hạn"?"soon":"ok")}>{slaLabel(x)}</span></td><td>{x.assignee||"Chưa phân công"}</td></tr>)}{!filtered.length&&<tr><td colSpan={8}>Không có yêu cầu phù hợp.</td></tr>}</tbody></table></div></section></main>}