"use client";
import Link from "next/link";
import { useEffect, useMemo, useState } from "react";
type Row={status?:string;priority?:string;count:number}; type Recent={ticket_no:string;title:string;status:string;priority:string;unit?:string;created_at:string};
type Stats={total:number;statuses:Row[];priorities:Row[];overdue:number;recent:Recent[]};
const statuses=["Open","Assigned","In Progress","Resolved","Closed"]; const priorities=["Critical","High","Normal","Low"];
const statusLabel=(s:string)=>s==="In Progress"?"Đang xử lý":s==="Assigned"?"Đã phân công":s==="Resolved"?"Đã xử lý":s==="Closed"?"Đã đóng":"Mở";
export default function Home(){
 const [stats,setStats]=useState<Stats|null>(null); const [error,setError]=useState("");
 useEffect(()=>{fetch("/api/tickets/stats").then(async r=>{const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể tải thống kê");return j}).then(setStats).catch(e=>setError(e instanceof Error?e.message:"Không thể tải thống kê"))},[]);
 const sm=useMemo(()=>new Map((stats?.statuses||[]).map(x=>[x.status,x.count])),[stats]); const pm=useMemo(()=>new Map((stats?.priorities||[]).map(x=>[x.priority,x.count])),[stats]);
 const ms=Math.max(1,...(stats?.statuses||[]).map(x=>x.count)); const mp=Math.max(1,...(stats?.priorities||[]).map(x=>x.count));
 return <main className="container"><div className="hero"><span className="eyebrow">Vinatex IT Operations</span><h1>IT Helpdesk Portal</h1><p>Cổng hỗ trợ kỹ thuật tập trung cho VPCTY và các đơn vị, nhà máy.</p></div>
 {error&&<div className="notice">Chưa kết nối được cơ sở dữ liệu: {error}</div>}
 <section className="metric-grid"><div className="metric-card"><span>Tổng Ticket</span><strong>{stats?.total??"—"}</strong><small>Tất cả yêu cầu</small></div><div className="metric-card"><span>Đang mở</span><strong>{sm.get("Open")??0}</strong><small>Chờ tiếp nhận</small></div><div className="metric-card"><span>Đang xử lý</span><strong>{(sm.get("Assigned")??0)+(sm.get("In Progress")??0)}</strong><small>Assigned + In Progress</small></div><div className="metric-card metric-alert"><span>Quá SLA</span><strong>{stats?.overdue??0}</strong><small>Chưa Resolved/Closed</small></div><div className="metric-card"><span>Critical</span><strong>{pm.get("Critical")??0}</strong><small>Ưu tiên cao nhất</small></div></section>
 <div className="dashboard-grid"><section className="panel"><div className="section-heading"><h2>Phân bổ trạng thái</h2><Link href="/tickets">Xem Ticket →</Link></div><div className="bar-list">{statuses.map(s=>{const n=sm.get(s)??0;return <div className="bar-row" key={s}><div className="bar-label"><span>{statusLabel(s)}</span><strong>{n}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:(n/ms)*100+"%"}}/></div></div>})}</div></section>
 <section className="panel"><div className="section-heading"><h2>Phân bổ ưu tiên</h2><Link href="/tickets">Danh sách →</Link></div><div className="bar-list">{priorities.map(s=>{const n=pm.get(s)??0;return <div className="bar-row" key={s}><div className="bar-label"><span>{s}</span><strong>{n}</strong></div><div className="bar-track"><div className="bar-fill" style={{width:(n/mp)*100+"%"}}/></div></div>})}</div></section></div>
 <section className="panel"><div className="section-heading"><h2>Ticket mới nhất</h2><Link href="/tickets/new">+ Tạo Ticket</Link></div>{stats?.recent?.length?<div className="table-wrap"><table><thead><tr><th>Ticket</th><th>Tiêu đề</th><th>Đơn vị</th><th>Trạng thái</th><th>Ưu tiên</th><th>Ngày tạo</th></tr></thead><tbody>{stats.recent.map(t=><tr key={t.ticket_no}><td><Link href={"/tickets/"+encodeURIComponent(t.ticket_no)}>{t.ticket_no}</Link></td><td>{t.title}</td><td>{t.unit||"-"}</td><td>{statusLabel(t.status)}</td><td>{t.priority}</td><td>{new Date(t.created_at).toLocaleString("vi-VN")}</td></tr>)}</tbody></table></div>:<p className="muted">Chưa có Ticket.</p>}</section>
 <div className="cards dashboard-links">{[["📚","Knowledge Base","Tra cứu tài liệu, case và script IT.","/knowledge-base"],["🎫","Ticket / Incident","Tiếp nhận và theo dõi yêu cầu hỗ trợ IT.","/tickets"],["🧰","Scripts","Kho PowerShell, CMD, Bash và công cụ xử lý.","/scripts"],["🛠️","IT Tools","Danh sách công cụ hỗ trợ kỹ thuật.","/tools"]].map(([i,t,d,h])=><Link className="card" href={h} key={h}><div style={{fontSize:28}}>{i}</div><h2>{t}</h2><p>{d}</p></Link>)}</div></main>}