"use client";
import {useEffect,useState} from "react";
type U={id:string;email:string;name:string;role:"user"|"it"|"admin";active:boolean};
export default function Users(){
 const [rows,setRows]=useState<U[]>([]),[error,setError]=useState(""),[form,setForm]=useState({email:"",name:"",password:"",role:"user"});
 async function load(){const r=await fetch("/api/admin/users");const j=await r.json();if(!r.ok){setError(j.error||"Không thể tải");return}setRows(j.users||[])}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setError(j.error||"Không thể tạo");return}setForm({email:"",name:"",password:"",role:"user"});load()}
 async function update(u:U,patch:Partial<U>&{password?:string}){const r=await fetch("/api/admin/users/"+u.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!r.ok){const j=await r.json();setError(j.error||"Không thể cập nhật");return}load()}
 return <main className="container"><div className="hero"><span className="eyebrow">Administration</span><h1>Quản lý người dùng</h1><p>Tạo tài khoản và phân quyền User / IT / Admin.</p></div>
 {error&&<div className="notice">{error}</div>}
 <form className="panel form" onSubmit={create}><div className="section-heading"><h2>Thêm tài khoản</h2></div><div className="form-grid"><label>Họ tên<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></label><label>Email<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/></label><label>Mật khẩu<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/></label><label>Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as U["role"]})}><option value="user">User</option><option value="it">IT</option><option value="admin">Admin</option></select></label></div><button>Tạo tài khoản</button></form>
 <section className="panel" style={{marginTop:16}}><div className="table-wrap"><table><thead><tr><th>Họ tên</th><th>Email</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{rows.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td><select value={u.role} onChange={e=>update(u,{role:e.target.value as U["role"]})}><option value="user">User</option><option value="it">IT</option><option value="admin">Admin</option></select></td><td>{u.active?"Đang hoạt động":"Đã khóa"}</td><td><button type="button" onClick={()=>update(u,{active:!u.active})}>{u.active?"Khóa":"Mở khóa"}</button></td></tr>)}</tbody></table></div></section></main>
}
