"use client";
import {useEffect,useMemo,useState} from "react";
type U={id:string;email:string;name:string;role:"user"|"it"|"admin";active:boolean};
const roles={user:"Người dùng",it:"Nhân viên CNTT",admin:"Quản trị viên"};
export default function Users(){
 const [rows,setRows]=useState<U[]>([]),[error,setError]=useState(""),[q,setQ]=useState(""),[form,setForm]=useState({email:"",name:"",password:"",role:"user"});
 async function load(){const r=await fetch("/api/admin/users");const j=await r.json();if(!r.ok){setError(j.error||"Không thể tải danh sách người dùng");return}setError("");setRows(j.users||[])}
 useEffect(()=>{load()},[]);
 async function create(e:React.FormEvent){e.preventDefault();setError("");const r=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setError(j.error||"Không thể tạo tài khoản");return}setForm({email:"",name:"",password:"",role:"user"});load()}
 async function update(u:U,patch:Partial<U>&{password?:string}){const r=await fetch("/api/admin/users/"+u.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});if(!r.ok){const j=await r.json();setError(j.error||"Không thể cập nhật");return}load()}
 const filtered=useMemo(()=>rows.filter(u=>(u.name+" "+u.email+" "+roles[u.role]).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const active=rows.filter(u=>u.active).length;
 return <main className="container users-page"><div className="page-heading-row"><div className="hero"><span className="eyebrow">Quản trị hệ thống</span><h1>Quản lý người dùng</h1><p>Tạo tài khoản, phân quyền và quản lý trạng thái truy cập hệ thống.</p></div></div>
 {error&&<div className="notice">{error}</div>}
 <section className="stats-grid users-stats"><div className="stat-card"><span>Tổng tài khoản</span><strong>{rows.length}</strong><small>Tất cả người dùng</small></div><div className="stat-card stat-success"><span>Đang hoạt động</span><strong>{active}</strong><small>Có thể đăng nhập</small></div><div className="stat-card"><span>Nhân viên CNTT</span><strong>{rows.filter(u=>u.role==="it").length}</strong><small>Tài khoản xử lý hỗ trợ</small></div><div className="stat-card"><span>Quản trị viên</span><strong>{rows.filter(u=>u.role==="admin").length}</strong><small>Quyền quản trị hệ thống</small></div></section>
 <div className="admin-layout"><form className="panel form account-form" onSubmit={create}><div className="panel-title-row"><div><h2>Thêm tài khoản</h2><p>Tạo người dùng mới và thiết lập quyền truy cập ban đầu.</p></div></div><div className="form-grid"><label>Họ và tên<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Nhập họ và tên"/></label><label>Thư điện tử<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} placeholder="ten@vinatexdn.com.vn"/></label><label>Mật khẩu<input required minLength={8} type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder="Tối thiểu 8 ký tự"/></label><label>Vai trò<select value={form.role} onChange={e=>setForm({...form,role:e.target.value as U["role"]})}><option value="user">Người dùng</option><option value="it">Nhân viên CNTT</option><option value="admin">Quản trị viên</option></select></label></div><button className="button" type="submit">+ Tạo tài khoản</button></form>
 <section className="panel data-panel users-list-panel"><div className="panel-title-row"><div><h2>Danh sách tài khoản</h2><p>{filtered.length} tài khoản hiển thị</p></div><div className="search-field user-search"><span aria-hidden="true">⌕</span><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm tên hoặc thư điện tử..."/></div></div><div className="table-wrap modern-table"><table><thead><tr><th>Người dùng</th><th>Thư điện tử</th><th>Vai trò</th><th>Trạng thái</th><th>Thao tác</th></tr></thead><tbody>{filtered.map(u=><tr key={u.id}><td><div className="user-table-person"><span className="table-avatar">{u.name?.trim()?.charAt(0)?.toUpperCase()||"U"}</span><strong>{u.name}</strong></div></td><td>{u.email}</td><td><select className="compact-select" value={u.role} onChange={e=>update(u,{role:e.target.value as U["role"]})}><option value="user">Người dùng</option><option value="it">Nhân viên CNTT</option><option value="admin">Quản trị viên</option></select></td><td><span className={u.active?"account-status active":"account-status locked"}><i/>{u.active?"Đang hoạt động":"Đã khóa"}</span></td><td><button className={u.active?"table-action danger":"table-action"} type="button" onClick={()=>update(u,{active:!u.active})}>{u.active?"Khóa tài khoản":"Mở khóa"}</button></td></tr>)}{!filtered.length&&<tr><td className="empty-cell" colSpan={5}>Không tìm thấy tài khoản phù hợp.</td></tr>}</tbody></table></div></section></div></main>
}