"use client";
import { useState } from "react";
type Source={title:string;path:string;type:string;url:string;relevance?:number};type Turn={role:"user"|"assistant";content:string};type TicketDraft={title:string;description:string;category:string;priority:string};
const quickQuestions=["Máy tính không kết nối được WiFi phải xử lý thế nào?","WiFi đã kết nối nhưng không có Internet, cần kiểm tra gì?","Máy in không in được, cần kiểm tra những bước nào?"];
export default function AiCopilot(){
 const [question,setQuestion]=useState(""),[turns,setTurns]=useState<Turn[]>([]),[sources,setSources]=useState<Source[]>([]),[loading,setLoading]=useState(false),[error,setError]=useState(""),[ticketMsg,setTicketMsg]=useState(""),[ticketNo,setTicketNo]=useState(""),[ticketDraft,setTicketDraft]=useState<TicketDraft|null>(null),[suggestTicket,setSuggestTicket]=useState(false);
 async function ask(q=question){const value=q.trim();if(!value||loading)return;setLoading(true);setError("");setTicketMsg("");setTicketDraft(null);setSuggestTicket(false);const next=[...turns,{role:"user" as const,content:value}];try{const r=await fetch("/api/ai/copilot",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({question:value,history:turns})});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể gọi trợ lý AI");setTurns([...next,{role:"assistant",content:j.answer||""}]);setSources(j.sources||[]);setTicketDraft(j.ticketDraft||null);setSuggestTicket(Boolean(j.suggestCreateTicket));setQuestion("")}catch(e){setError(e instanceof Error?e.message:"Có lỗi xảy ra")}finally{setLoading(false)}}
 async function createTicket(){if(!ticketDraft){setTicketMsg("Chưa có đủ thông tin để tạo yêu cầu hỗ trợ.");return}setTicketMsg("Đang tạo yêu cầu hỗ trợ...");setTicketNo("");try{const r=await fetch("/api/tickets",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(ticketDraft)});const j=await r.json();if(!r.ok)throw new Error(j.error||"Không thể tạo yêu cầu");setTicketNo(j.ticket.ticket_no);setTicketMsg("Đã tạo "+j.ticket.ticket_no+". Bộ phận CNTT có thể tiếp tục xử lý.")}catch(e){setTicketMsg(e instanceof Error?e.message:"Không thể tạo yêu cầu")}}
 return <section className="ai-box kb-copilot modern-kb-ai"><div className="kb-copilot-head"><span className="kb-ai-logo">AI</span><div><strong>Trợ lý CNTT Vinatex</strong><p>Hỏi về sự cố CNTT và nhận hướng dẫn dựa trên tài liệu nội bộ được phép truy cập.</p></div><span className="kb-ai-status">● Sẵn sàng</span></div>{turns.length===0&&<div className="kb-ai-welcome"><strong>Tôi có thể hỗ trợ bạn vấn đề gì?</strong><p>Chọn một câu hỏi gợi ý hoặc mô tả sự cố đang gặp phải.</p><div className="kb-quick">{quickQuestions.map(q=><button key={q} type="button" onClick={()=>ask(q)}>{q}<span>→</span></button>)}</div></div>}{turns.length>0&&<div className="kb-chat">{turns.map((t,i)=><div key={i} className={"kb-msg "+t.role}><div className="kb-msg-label">{t.role==="user"?"Bạn":"Trợ lý AI"}</div><div className="kb-msg-body">{t.content}</div></div>)}</div>}{suggestTicket&&ticketDraft&&<div className="notice"><strong>Nên chuyển yêu cầu này cho bộ phận CNTT.</strong><br/>Trợ lý đã chuẩn bị sẵn: <b>{ticketDraft.category}</b> · Mức độ <b>{ticketDraft.priority}</b>. Bạn có thể tạo yêu cầu chỉ với một lần bấm.</div>}<div className="kb-question"><textarea value={question} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();ask()}}} placeholder="Mô tả sự cố hoặc đặt câu hỏi cho trợ lý AI..." aria-label="Câu hỏi cho Trợ lý AI"/><button type="button" onClick={()=>ask()} disabled={loading||!question.trim()}>{loading?"Đang phân tích...":"Gửi câu hỏi"}</button></div><small className="kb-ai-hint">Enter để gửi · Shift + Enter để xuống dòng</small>{error&&<div className="kb-ai-error">{error}</div>}{turns.length>0&&<div className="kb-actions"><button type="button" onClick={createTicket} disabled={!ticketDraft}>{suggestTicket?"Tạo yêu cầu hỗ trợ ngay":"Tạo yêu cầu hỗ trợ từ trao đổi"}</button><button type="button" className="kb-secondary" onClick={()=>{setTurns([]);setSources([]);setError("");setTicketMsg("");setTicketDraft(null);setSuggestTicket(false)}}>Cuộc trao đổi mới</button></div>}{ticketMsg&&<div className="notice">{ticketMsg}{ticketNo&&<> · <a href={"/tickets/"+encodeURIComponent(ticketNo)}>Xem yêu cầu →</a></>}</div>}{sources.length>0&&<div className="ai-sources kb-source-list"><strong>Nguồn tham khảo trong Kho kiến thức</strong>{sources.map((s,i)=><a key={s.path} href={"/knowledge-base/document?path="+encodeURIComponent(s.path)}><span className="source-index">{i+1}</span><span><b>{s.title}</b><small>{s.path}{s.relevance?` · Độ liên quan ${s.relevance}`:""}</small></span><em>→</em></a>)}</div>}</section>
}
